begin;
select no_plan();

select hasnt_table(
  'public',
  'recommendations',
  'the generic Recommendation table is retired'
);
select hasnt_table(
  'public',
  'decision_feedback',
  'the Decision Feedback table is retired'
);
select hasnt_column(
  'public',
  'daily_briefings',
  'recommendation_ids',
  'Daily Briefings no longer store Recommendation ids'
);

select is_empty(
  $$select id from public.daily_briefings$$,
  'legacy Daily Briefing content is erased'
);
select is_empty(
  $$select id from public.weekly_reviews$$,
  'legacy Weekly Review content is erased'
);
select is_empty(
  $$select id from public.coach_messages$$,
  'Coach messages are erased'
);
select is_empty(
  $$select memory_id from public.coach_memory_selections$$,
  'Coach memory selections are erased'
);

select ok(
  (
    select state = 'deleted'
      and prompt_version = 'free-coach-agent-prompt-v4'
      and context_version = 'personal-snapshot-v3'
      and context_parameters = '{}'::jsonb
      and message_fingerprint is null
      and response is null
      and used_context = '[]'::jsonb
      and error is null
      and evidence is null
      and agent_trace is null
      and tool_call_count is null
      and service_tier is null
      and deleted_at is not null
    from public.coach_requests
    where request_id = 'f7000000-0000-4000-8000-000000000801'
  ),
  'the Coach request identity survives only as a normalized content-free tombstone'
);
select is(
  (
    select count(*)::bigint
    from public.coach_usage_events
    where request_id = 'f7000000-0000-4000-8000-000000000801'
      and outcome = 'failed'
      and error_code = 'interrupted'
  ),
  1::bigint,
  'append-only Coach usage evidence survives exactly once'
);
select ok(
  (
    select state = 'deleted'
      and contract_version = 'coach-request-v1'
      and prompt_version = 'controlled-coach-prompt-v1'
      and context_version = 'coach-context-v1'
      and context_parameters = '{}'::jsonb
      and message_fingerprint is null
      and response is null
      and used_context = '[]'::jsonb
      and error is null
      and evidence is null
      and agent_trace is null
      and tool_call_count is null
      and service_tier is null
      and deleted_at is not null
    from public.coach_requests
    where request_id = 'f7000000-0000-4000-8000-000000000802'
      and user_id = 'f7000000-0000-4000-8000-000000000002'
  ),
  'a historical V1 request keeps only its allowed content-free identity'
);
select ok(
  (
    select state = 'deleted'
      and contract_version = 'coach-request-v2'
      and prompt_version = 'controlled-coach-prompt-v3'
      and context_version = 'coach-context-v3'
      and context_parameters = '{}'::jsonb
      and message_fingerprint is null
      and response is null
      and used_context = '[]'::jsonb
      and error is null
      and evidence is null
      and agent_trace is null
      and tool_call_count is null
      and service_tier is null
      and deleted_at is not null
    from public.coach_requests
    where request_id = 'f7000000-0000-4000-8000-000000000803'
      and user_id = 'f7000000-0000-4000-8000-000000000002'
  ),
  'a historical V2 request keeps only its allowed content-free identity'
);
select is(
  (
    select count(*)::bigint
    from public.coach_usage_events
    where request_id in (
      'f7000000-0000-4000-8000-000000000802',
      'f7000000-0000-4000-8000-000000000803'
    )
      and user_id = 'f7000000-0000-4000-8000-000000000002'
      and outcome = 'failed'
      and error_code = 'interrupted'
  ),
  2::bigint,
  'both historical usage identities survive exactly for the second owner'
);
select is(
  (
    select count(*)::bigint
    from public.profiles
    where id in (
      'f7000000-0000-4000-8000-000000000001',
      'f7000000-0000-4000-8000-000000000002'
    )
  ),
  2::bigint,
  'retirement erases generated content without deleting either owner'
);

select is_empty(
  $$
    select id from public.notifications
    where id = 'f7000000-0000-4000-8000-000000000601'
  $$,
  'the exactly typed legacy Briefing notification is erased'
);
select is_empty(
  $$
    select request_id from public.notification_action_requests
    where request_id = 'f7000000-0000-4000-8000-000000000611'
  $$,
  'the typed notification retry row follows its established cascade'
);
select ok(
  (
    select title = 'Imported note'
      and message = 'This is not generated by the Briefing contract.'
      and metadata = '{
        "source_kind":"daily_briefing",
        "ordinary":"keep exactly"
      }'::jsonb
    from public.notifications
    where id = 'f7000000-0000-4000-8000-000000000602'
  ),
  'an untyped notification is retained exactly'
);
select ok(
  (
    select title = 'Daily state check-in'
      and message = 'Open Today when you are ready.'
      and type = 'coaching'
      and priority = 'low'
      and action_url = '/dashboard'
      and due_at = '2026-08-13T10:00:00Z'::timestamptz
      and generation_key =
        'notification-generation-v1:recovery_prompt:2026-08-13'
      and generation_category = 'recovery_prompt'
      and delivery_date = '2026-08-13'
      and metadata = '{
        "contract_version":"notification-generation-v1",
        "origin":"deterministic_backend",
        "category":"recovery_prompt",
        "reason_code":"current_daily_state",
        "delivery_date":"2026-08-13",
        "timezone":"Europe/Berlin",
        "source_kind":"daily_state",
        "source_id":"f7000000-0000-4000-8000-000000000301",
        "source_generated_at":"2026-08-13T08:15:00Z",
        "sensitive_copy_excluded":true,
        "llm_used":false
      }'::jsonb
    from public.notifications
    where id = 'f7000000-0000-4000-8000-000000000603'
  ),
  'a typed Daily State notification is retained exactly'
);
select ok(
  (
    select notification_id = 'f7000000-0000-4000-8000-000000000603'
      and user_id = 'f7000000-0000-4000-8000-000000000001'
      and contract_version = 'notification-lifecycle-v1'
      and command = 'mark_read'
      and result_is_read
      and result_updated_at = '2026-08-13T10:01:00Z'::timestamptz
    from public.notification_action_requests
    where request_id = 'f7000000-0000-4000-8000-000000000612'
  ),
  'the retained typed notification action identity remains exact'
);

select ok(
  (
    select not (responses ? 'recommendations')
      and responses ->> 'note' =
        'The word recommendation in prose must remain.'
      and responses -> 'user_feedback' = '{"rating":4}'::jsonb
      and metadata -> 'sources' = '["tasks"]'::jsonb
      and metadata ->> 'ordinary' = 'feedback in ordinary prose remains'
    from public.intake_responses
    where id = 'f7000000-0000-4000-8000-000000000101'
  ),
  'Intake loses only retired structured fields and sources'
);
select ok(
  (
    select not (metadata ? 'recommendation_id')
      and metadata ->> 'note' = 'Keep this recommendation sentence.'
      and metadata -> 'user_feedback' = '{"rating":5}'::jsonb
    from public.tasks
    where id = 'f7000000-0000-4000-8000-000000000201'
  ),
  'Task metadata keeps independent payload and prose'
);
select ok(
  (
    select not (summary ? 'recommendation_ids')
      and summary ->> 'note' = 'recommendation prose remains'
      and signals -> 'sources' = '["tasks"]'::jsonb
      and metadata = '{}'::jsonb
    from public.user_state_snapshots
    where id = 'f7000000-0000-4000-8000-000000000301'
  ),
  'snapshot JSON is sanitized structurally without prose matching'
);

select ok(
  (
    select type = 'recommendation'
      and title = 'Retained memory advice'
      and content = 'This normal memory content remains byte-for-byte.'
      and strength = 0.7
      and evidence = '[{"source":"tasks","id":"task-1"}]'::jsonb
      and metadata = '{
        "ordinary":"recommendation prose",
        "user_feedback":{"rating":5}
      }'::jsonb
    from public.memory_entries
    where id = 'f7000000-0000-4000-8000-000000000701'
  ),
  'the preserved Recommendation memory kind and its normal content are exact'
);
select ok(
  (
    select recommendation = 'Keep a stable wind-down window.'
      and source = 'ai-engine'
      and category = 'sleep'
      and metadata = '{
        "ordinary":"feedback prose",
        "user_feedback":{"rating":4}
      }'::jsonb
    from public.ai_insights
    where id = 'f7000000-0000-4000-8000-000000000711'
  ),
  'the independent AI Insight recommendation field is retained exactly'
);
select is_empty(
  $$
    select id from public.ai_insights
    where id = 'f7000000-0000-4000-8000-000000000712'
  $$,
  'an Insight with retired source/category identifiers is removed'
);
select ok(
  (
    select metadata = '{"ordinary":"recommendation prose remains"}'::jsonb
    from public.behavioral_events
    where id = 'f7000000-0000-4000-8000-000000000721'
  ),
  'a normal event is retained with only its typed reference removed'
);
select is_empty(
  $$
    select id from public.behavioral_events
    where id = 'f7000000-0000-4000-8000-000000000722'
  $$,
  'an event with retired source/type identifiers is removed'
);
select ok(
  (
    select overall_score = 72
      and archetype = 'Steady learner'
      and scores = '[{"skill":"planning","score":72}]'::jsonb
    from public.skillset_profiles
    where id = 'f7000000-0000-4000-8000-000000000731'
  ),
  'Skillset remains untouched'
);

select ok(
  to_regprocedure(
    'public.persist_weekly_review_v2(uuid,text,timestamp with time zone,jsonb)'
  ) is null
    and to_regprocedure(
      'public.replace_current_recommendations_v2(uuid,jsonb,timestamp with time zone)'
    ) is null,
  'retired Weekly V2 and Recommendation writer RPCs are absent'
);
select ok(
  to_regprocedure(
    'public.persist_weekly_review_v3(uuid,text,timestamp with time zone,jsonb)'
  ) is not null
    and to_regprocedure(
      'public.claim_coach_request_v6(uuid,uuid,text,date,text,text,text,text,timestamp with time zone,timestamp with time zone,integer)'
    ) is not null,
  'current Weekly V3 and Coach V6 writer RPCs exist'
);
select is(
  (
    select proconfig
    from pg_proc
    where oid =
      'public.persist_weekly_review_v3(uuid,text,timestamp with time zone,jsonb)'::regprocedure
  ),
  array['search_path=pg_catalog, pg_temp']::text[],
  'Weekly V3 fixes its SECURITY DEFINER search path'
);
select is(
  (
    select proconfig
    from pg_proc
    where oid =
      'public.create_generated_notification_v1(uuid,uuid,text,text,date,timestamp with time zone,text,text,text,text,text,text,text,text,text,timestamp with time zone)'::regprocedure
  ),
  array['search_path=pg_catalog, pg_temp']::text[],
  'the retained notification writer fixes its SECURITY DEFINER search path'
);
select ok(
  strpos(
    pg_get_functiondef(
      'public.create_generated_notification_v1(uuid,uuid,text,text,date,timestamp with time zone,text,text,text,text,text,text,text,text,text,timestamp with time zone)'::regprocedure
    ),
    '''daily_briefing'''
  ) = 0,
  'the current notification writer has no executable Daily Briefing source'
);
select ok(
  has_function_privilege(
    'service_role',
    'public.persist_weekly_review_v3(uuid,text,timestamp with time zone,jsonb)',
    'EXECUTE'
  )
    and not has_function_privilege(
      'authenticated',
      'public.persist_weekly_review_v3(uuid,text,timestamp with time zone,jsonb)',
      'EXECUTE'
    )
    and not has_function_privilege(
      'anon',
      'public.persist_weekly_review_v3(uuid,text,timestamp with time zone,jsonb)',
      'EXECUTE'
    ),
  'Weekly V3 remains service-role-only'
);
select ok(
  has_function_privilege(
    'service_role',
    'public.claim_coach_request_v6(uuid,uuid,text,date,text,text,text,text,timestamp with time zone,timestamp with time zone,integer)',
    'EXECUTE'
  )
    and not has_function_privilege(
      'authenticated',
      'public.claim_coach_request_v6(uuid,uuid,text,date,text,text,text,text,timestamp with time zone,timestamp with time zone,integer)',
      'EXECUTE'
    )
    and not has_function_privilege(
      'anon',
      'public.claim_coach_request_v6(uuid,uuid,text,date,text,text,text,text,timestamp with time zone,timestamp with time zone,integer)',
      'EXECUTE'
    )
    and not has_function_privilege(
      'service_role',
      'public.claim_coach_request_v5(uuid,uuid,text,date,text,text,text,text,timestamp with time zone,timestamp with time zone,integer)',
      'EXECUTE'
    ),
  'Coach V6 replaces V5 as the service-role-only free-agent claim authority'
);
select ok(
  has_function_privilege(
    'service_role',
    'public.claim_coach_request_v1(uuid,uuid,text,text,date,text,text,text,text,text,text,timestamp with time zone,timestamp with time zone,integer)',
    'EXECUTE'
  )
    and has_function_privilege(
      'service_role',
      'public.claim_coach_request_v2(uuid,uuid,text,text,jsonb,date,text,text,text,text,text,text,timestamp with time zone,timestamp with time zone,integer)',
      'EXECUTE'
    )
    and not has_function_privilege(
      'authenticated',
      'public.claim_coach_request_v1(uuid,uuid,text,text,date,text,text,text,text,text,text,timestamp with time zone,timestamp with time zone,integer)',
      'EXECUTE'
    )
    and not has_function_privilege(
      'authenticated',
      'public.claim_coach_request_v2(uuid,uuid,text,text,jsonb,date,text,text,text,text,text,text,timestamp with time zone,timestamp with time zone,integer)',
      'EXECUTE'
    ),
  'controlled Coach V1 and longitudinal V2 remain backend-only writers'
);
select ok(
  has_function_privilege(
    'service_role',
    'private.references_retired_recommendation_v1(jsonb)',
    'EXECUTE'
  )
    and not has_function_privilege(
      'authenticated',
      'private.references_retired_recommendation_v1(jsonb)',
      'EXECUTE'
    )
    and not has_function_privilege(
      'anon',
      'private.references_retired_recommendation_v1(jsonb)',
      'EXECUTE'
    )
    and to_regprocedure(
      'private.sanitize_retired_recommendation_v1(jsonb)'
    ) is null,
  'only the service-role guard needed by direct writes remains executable'
);
select is(
  (
    select count(*)::bigint
    from pg_class
    where oid in (
      'public.coach_requests'::regclass,
      'public.daily_briefings'::regclass,
      'public.notifications'::regclass,
      'public.weekly_reviews'::regclass
    )
      and relrowsecurity
      and relforcerowsecurity
  ),
  4::bigint,
  'RLS and forced RLS remain enabled on every changed content table'
);
select ok(
  has_table_privilege(
    'authenticated', 'public.daily_briefings', 'SELECT'
  )
    and not has_table_privilege(
      'authenticated', 'public.daily_briefings', 'INSERT,UPDATE,DELETE'
    )
    and has_table_privilege(
      'authenticated', 'public.weekly_reviews', 'SELECT'
    )
    and not has_table_privilege(
      'authenticated', 'public.weekly_reviews', 'INSERT,UPDATE,DELETE'
    )
    and has_table_privilege(
      'service_role', 'public.daily_briefings', 'SELECT,INSERT,UPDATE,DELETE'
    )
    and has_table_privilege(
      'service_role', 'public.weekly_reviews', 'SELECT,INSERT,UPDATE,DELETE'
    ),
  'existing table grants remain least-privilege and writer-compatible'
);

set local role service_role;

select lives_ok(
  $$
    insert into public.daily_briefings (
      user_id, briefing_date, mode, summary, primary_action, support_actions,
      evidence_refs, provenance, data_quality, metadata, generated_at, updated_at
    ) values (
      'f7000000-0000-4000-8000-000000000001',
      '2026-08-14',
      'steady',
      'Current deterministic briefing.',
      '{
        "target":{"kind":"planning"},
        "title":"Review Today",
        "reason":"Use the current plan.",
        "evidence_refs":[]
      }'::jsonb,
      '[]'::jsonb,
      '[]'::jsonb,
      '{
        "engine":"deterministic",
        "contract_version":"daily-briefing-v2",
        "daily_state_contract_version":"explainable-daily-state-v3",
        "executable_action_contract_version":"executable-action-v1",
        "source_snapshot_id":"f7000000-0000-4000-8000-000000000301",
        "source_snapshot_generated_at":"2026-08-13T08:15:00Z",
        "baseline":"none",
        "llm_used":false
      }'::jsonb,
      'current',
      '{
        "contract_version":"daily-briefing-v2",
        "capacity_note":"A balanced plan.",
        "ranking_version":"deterministic-briefing-ranker-v3",
        "candidate_count":1
      }'::jsonb,
      '2026-08-14T08:00:00Z',
      '2026-08-14T08:00:00Z'
    )
  $$,
  'service_role can directly persist a valid Daily Briefing V2 row'
);

select throws_ok(
  $$
    insert into public.daily_briefings (
      user_id, briefing_date, mode, summary, primary_action, support_actions,
      evidence_refs, provenance, data_quality, metadata, generated_at, updated_at
    ) values (
      'f7000000-0000-4000-8000-000000000001',
      '2026-08-15', 'steady', 'Legacy contract.',
      '{}', '[]', '[]',
      '{"engine":"deterministic","contract_version":"daily-briefing-v1"}',
      'current',
      '{
        "contract_version":"daily-briefing-v1",
        "ranking_version":"deterministic-briefing-ranker-v2"
      }',
      '2026-08-15T08:00:00Z', '2026-08-15T08:00:00Z'
    )
  $$,
  '23514',
  null,
  'service_role cannot persist a Daily Briefing V1 row'
);

select throws_ok(
  $$
    insert into public.daily_briefings (
      user_id, briefing_date, mode, summary, primary_action, support_actions,
      evidence_refs, provenance, data_quality, metadata, generated_at, updated_at
    ) values (
      'f7000000-0000-4000-8000-000000000001',
      '2026-08-16', 'steady', 'Retired source.',
      '{"recommendation_id":"legacy"}', '[]', '[]',
      '{
        "engine":"deterministic",
        "contract_version":"daily-briefing-v2",
        "baseline":"none",
        "llm_used":false
      }',
      'current',
      '{
        "contract_version":"daily-briefing-v2",
        "ranking_version":"deterministic-briefing-ranker-v3"
      }',
      '2026-08-16T08:00:00Z', '2026-08-16T08:00:00Z'
    )
  $$,
  '23514',
  null,
  'service_role cannot persist a retired Recommendation reference'
);

select is(
  public.create_generated_notification_v1(
    'f7000000-0000-4000-8000-000000000001',
    'f7000000-0000-4000-8000-000000000604',
    'notification-generation-v1:recovery_prompt:2026-08-14',
    'recovery_prompt',
    '2026-08-14',
    '2026-08-14T08:00:00Z',
    'Europe/Berlin',
    'Current daily state',
    'Open Today.',
    'coaching',
    'low',
    '/dashboard',
    'current_daily_state',
    'daily_state',
    'f7000000-0000-4000-8000-000000000301',
    '2026-08-13T08:15:00Z'
  ),
  '{
    "status":"created",
    "notification_id":"f7000000-0000-4000-8000-000000000604"
  }'::jsonb,
  'the retained generator creates from the current Daily State source'
);
select ok(
  (
    select id = 'f7000000-0000-4000-8000-000000000604'
      and user_id = 'f7000000-0000-4000-8000-000000000001'
      and title = 'Current daily state'
      and message = 'Open Today.'
      and type = 'coaching'
      and priority = 'low'
      and not is_read
      and read_at is null
      and dismissed_at is null
      and action_url = '/dashboard'
      and due_at = '2026-08-14T08:00:00Z'::timestamptz
      and generation_key =
        'notification-generation-v1:recovery_prompt:2026-08-14'
      and generation_category = 'recovery_prompt'
      and delivery_date = '2026-08-14'
      and in_app_delivered_at is null
      and created_at = '2026-08-14T08:00:00Z'::timestamptz
      and updated_at = '2026-08-14T08:00:00Z'::timestamptz
      and metadata = '{
        "contract_version":"notification-generation-v1",
        "origin":"deterministic_backend",
        "category":"recovery_prompt",
        "reason_code":"current_daily_state",
        "delivery_date":"2026-08-14",
        "timezone":"Europe/Berlin",
        "source_kind":"daily_state",
        "source_id":"f7000000-0000-4000-8000-000000000301",
        "source_generated_at":"2026-08-13T08:15:00+00:00",
        "sensitive_copy_excluded":true,
        "llm_used":false
      }'::jsonb
    from public.notifications
    where id = 'f7000000-0000-4000-8000-000000000604'
  ),
  'the current-source notification persists exact owner, generation, and provenance facts'
);
select throws_ok(
  $$
    select public.create_generated_notification_v1(
      'f7000000-0000-4000-8000-000000000001',
      'f7000000-0000-4000-8000-000000000606',
      'notification-generation-v1:null-category:2026-08-14',
      null,
      '2026-08-14',
      '2026-08-14T08:00:00Z',
      'Europe/Berlin',
      'Invalid category',
      'Open Today.',
      'reminder',
      'medium',
      '/dashboard',
      'current_daily_state',
      'daily_state',
      'f7000000-0000-4000-8000-000000000301',
      '2026-08-13T08:15:00Z'
    )
  $$,
  '22023',
  null,
  'the generator rejects a NULL category before owner reads'
);
select throws_ok(
  $$
    select public.create_generated_notification_v1(
      'f7000000-0000-4000-8000-000000000001',
      'f7000000-0000-4000-8000-000000000607',
      'notification-generation-v1:null-type:2026-08-14',
      'recovery_prompt',
      '2026-08-14',
      '2026-08-14T08:00:00Z',
      'Europe/Berlin',
      'Invalid type',
      'Open Today.',
      null,
      'medium',
      '/dashboard',
      'current_daily_state',
      'daily_state',
      'f7000000-0000-4000-8000-000000000301',
      '2026-08-13T08:15:00Z'
    )
  $$,
  '22023',
  null,
  'the generator rejects a NULL notification type before owner reads'
);
select throws_ok(
  $$
    select public.create_generated_notification_v1(
      'f7000000-0000-4000-8000-000000000001',
      'f7000000-0000-4000-8000-000000000608',
      'notification-generation-v1:null-priority:2026-08-14',
      'recovery_prompt',
      '2026-08-14',
      '2026-08-14T08:00:00Z',
      'Europe/Berlin',
      'Invalid priority',
      'Open Today.',
      'reminder',
      null,
      '/dashboard',
      'current_daily_state',
      'daily_state',
      'f7000000-0000-4000-8000-000000000301',
      '2026-08-13T08:15:00Z'
    )
  $$,
  '22023',
  null,
  'the generator rejects a NULL priority before owner reads'
);
select throws_ok(
  $$
    select public.create_generated_notification_v1(
      'f7000000-0000-4000-8000-000000000001',
      'f7000000-0000-4000-8000-000000000609',
      'notification-generation-v1:null-action:2026-08-14',
      'recovery_prompt',
      '2026-08-14',
      '2026-08-14T08:00:00Z',
      'Europe/Berlin',
      'Invalid action',
      'Open Today.',
      'reminder',
      'medium',
      null,
      'current_daily_state',
      'daily_state',
      'f7000000-0000-4000-8000-000000000301',
      '2026-08-13T08:15:00Z'
    )
  $$,
  '22023',
  null,
  'the generator rejects a NULL action URL before owner reads'
);
select throws_ok(
  $$
    select public.create_generated_notification_v1(
      'f7000000-0000-4000-8000-000000000001',
      'f7000000-0000-4000-8000-000000000610',
      'notification-generation-v1:null-source:2026-08-14',
      'recovery_prompt',
      '2026-08-14',
      '2026-08-14T08:00:00Z',
      'Europe/Berlin',
      'Invalid source',
      'Open Today.',
      'reminder',
      'medium',
      '/dashboard',
      'current_daily_state',
      null,
      'f7000000-0000-4000-8000-000000000301',
      '2026-08-13T08:15:00Z'
    )
  $$,
  '22023',
  null,
  'the generator rejects a NULL source kind before owner reads'
);
select throws_ok(
  $$
    select public.create_generated_notification_v1(
      'f7000000-0000-4000-8000-000000000001',
      'f7000000-0000-4000-8000-000000000605',
      'notification-generation-v1:recovery_prompt:2026-08-14',
      'recovery_prompt',
      '2026-08-14',
      '2026-08-14T08:00:00Z',
      'Europe/Berlin',
      'Legacy briefing',
      'Open Today.',
      'coaching',
      'low',
      '/dashboard',
      'legacy_daily_briefing',
      'daily_briefing',
      'f7000000-0000-4000-8000-000000000411',
      '2026-08-13T08:25:00Z'
    )
  $$,
  '22023',
  null,
  'the generator rejects the retired Daily Briefing source'
);

select lives_ok(
  $$
    select public.persist_weekly_review_v3(
      'f7000000-0000-4000-8000-000000000001',
      '2026-W32',
      '2026-08-09T18:00:00Z',
      '{
        "user_id":"f7000000-0000-4000-8000-000000000001",
        "period_key":"2026-W32",
        "week_start":"2026-08-03",
        "week_end":"2026-08-09",
        "timezone":"Europe/Berlin",
        "data_quality":"sufficient",
        "narrative":"Current observational review.",
        "facts":{
          "tasks":{"completed":1,"carried":0},
          "habits":{"completed":1,"skipped":0},
          "focus":{"actual_minutes":30},
          "recovery":{"recovery_days":0}
        },
        "proposals":[],
        "evidence_refs":[],
        "provenance":{
          "engine":"deterministic",
          "contract_version":"weekly-review-v3",
          "source_snapshot_id":"f7000000-0000-4000-8000-000000000302",
          "source_snapshot_generated_at":"2026-08-09T18:00:00Z",
          "evidence_window":{
            "starts_on":"2026-08-03",
            "ends_on":"2026-08-09",
            "days":7
          },
          "source_fingerprint":"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
          "baseline":"none",
          "limitations":[],
          "llm_used":false
        },
        "source_fingerprint":"cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
        "generated_at":"2026-08-09T18:01:00Z",
        "created_at":"2026-08-09T18:01:00Z",
        "updated_at":"2026-08-09T18:01:00Z"
      }'::jsonb
    )
  $$,
  'service_role can persist a strict Weekly Review V3 row'
);
select throws_ok(
  $$
    select public.persist_weekly_review_v3(
      'f7000000-0000-4000-8000-000000000002',
      '2026-W32',
      '2026-08-09T18:00:00Z',
      '{
        "user_id":"f7000000-0000-4000-8000-000000000002",
        "period_key":"2026-W32",
        "week_start":"2026-08-03",
        "week_end":"2026-08-09",
        "timezone":"America/New_York",
        "data_quality":"sufficient",
        "narrative":"Invalid retired feedback review.",
        "facts":{
          "tasks":{"completed":1,"carried":0},
          "habits":{"completed":1,"skipped":0},
          "focus":{"actual_minutes":30},
          "recovery":{"recovery_days":0},
          "feedback":{"done":1}
        },
        "proposals":[],
        "evidence_refs":[],
        "provenance":{
          "engine":"deterministic",
          "contract_version":"weekly-review-v3",
          "source_snapshot_id":"f7000000-0000-4000-8000-000000000303",
          "source_snapshot_generated_at":"2026-08-09T18:00:00Z",
          "evidence_window":{
            "starts_on":"2026-08-03",
            "ends_on":"2026-08-09",
            "days":7
          },
          "source_fingerprint":"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
          "baseline":"none",
          "limitations":[],
          "llm_used":false
        },
        "source_fingerprint":"dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
        "generated_at":"2026-08-09T18:01:00Z",
        "created_at":"2026-08-09T18:01:00Z",
        "updated_at":"2026-08-09T18:01:00Z"
      }'::jsonb
    )
  $$,
  '22023',
  null,
  'Weekly Review V3 rejects a retired Feedback fact'
);

select is(
  public.claim_coach_request_v6(
    'f7000000-0000-4000-8000-000000000001',
    'f7000000-0000-4000-8000-000000000804',
    repeat('e', 64),
    '2026-08-14',
    'fake',
    'deterministic_test_only',
    null,
    'not_applicable',
    '2026-08-14T09:00:00Z',
    '2026-08-14T09:02:00Z',
    20
  ) ->> 'state',
  'pending',
  'Coach V6 creates only the current prompt and snapshot pair'
);
select ok(
  (
    select contract_version = 'coach-request-v3'
      and prompt_version = 'free-coach-agent-prompt-v4'
      and context_version = 'personal-snapshot-v3'
    from public.coach_requests
    where request_id = 'f7000000-0000-4000-8000-000000000804'
  ),
  'the Coach V6 persisted version pair is exact'
);

reset role;

select * from finish();
rollback;
