import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

void main() {
  test(
    'student-facing presentation source stays English and avoids old terms',
    () {
      final presentationSources = Directory('lib/features')
          .listSync(recursive: true)
          .whereType<File>()
          .where(
            (file) =>
                file.path.endsWith('.dart') &&
                file.path.replaceAll('\\', '/').contains('/presentation/'),
          )
          .toList(growable: false);
      expect(presentationSources, isNotEmpty);

      final combined = presentationSources
          .map((file) => file.readAsStringSync())
          .join();
      // Only the explicitly selected German speaking guide is localized.
      final germanGuide = RegExp(
        r"if \(ref.read\(assistantLanguageProvider\('capture'\)\).value == 'de'\) \{[\s\S]*?\r?\n    \}",
      );
      for (final file in presentationSources) {
        var englishSource = file.readAsStringSync();
        if (file.path.replaceAll('\\', '/').endsWith(
            '/quick_action/presentation/pages/ultra_quick_check_in_page.dart')) {
          expect(germanGuide.allMatches(englishSource), hasLength(1));
          englishSource = englishSource.replaceFirst(germanGuide, '');
        }
        expect(englishSource, isNot(matches(RegExp(r'[äöüÄÖÜß]'))),
            reason: file.path);
      }

      const retiredVisiblePhrases = <String>[
        "'Morning Calibration'",
        "'Evening Shutdown'",
        "'Add signal'",
        "'Stress controllability'",
        "'In-app notifications'",
        "'Retry exact",
        "'Deterministic · no LLM'",
        "'Generated from",
        "'Coach ready'",
        'Configure Supabase',
        'Supabase is not configured',
        'Supabase Auth',
        'Supabase OAuth',
        'V4 export',
        'canonical synced',
        'owner-scoped',
        'The backend',
        'the backend',
        'active revision',
        'No demo',
        'No empty',
        'not AI',
        'AI-written',
        'not generated by AI',
        "'Login'",
        "'Register'",
        'return to login',
      ];
      for (final phrase in retiredVisiblePhrases) {
        expect(combined, isNot(contains(phrase)), reason: phrase);
      }
    },
  );

  test('capability-limited surfaces include their required plain truth', () {
    final notifications = File(
      'lib/features/notifications/presentation/pages/notification_settings_page.dart',
    ).readAsStringSync();
    expect(
      notifications,
      contains('These banners appear only while the app is open.'),
    );
    expect(
      notifications,
      contains('Android push is configured separately in Push reminders.'),
    );
    expect(notifications, contains('never includes private check-in details'));

    final coach = File(
      'lib/features/coach/presentation/pages/coach_page.dart',
    ).readAsStringSync();
    final coachModes = File(
      'lib/composition/widgets/coach_provider_settings_card.dart',
    ).readAsStringSync();
    expect(coach, contains('CoachProviderSettingsCard('));
    expect(
      coachModes,
      contains('Project Coach uses a temporary read-only snapshot on the VPS.'),
    );
    expect(
      coachModes,
      contains('Only your question and queried results reach the shared pilot'),
    );
    expect(
      coachModes,
      contains('Requests may cost money. Your question and relevant read-only'),
    );
    expect(coachModes, contains('No automatic provider fallback.'));
    expect(coach, contains('Local development-only agent'));
    expect(coach, contains('This is not a production service'));

    final insights = Directory('lib/features/insights/presentation')
        .listSync(recursive: true)
        .whereType<File>()
        .where((file) => file.path.endsWith('.dart'))
        .map((file) => file.readAsStringSync())
        .join();
    expect(insights, contains('EXAMPLE SKILL PROFILE'));
    expect(insights, contains('example data only'));
  });
}
